version: "3"
services:
  db:
    build: ./docker/mysql
    container_name: db
    restart: always
    hostname: db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: sortie
      MYSQL_USER: sortie
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d